name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Makefile'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    # Skip CI for dependabot PRs; still runs on main after merge when paths match
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv and deps
        run: |
          python -m pip install --upgrade pip
          pip install uv
          # Install project with dev extra (includes ruff, pytest, etc.)
          uv sync --extra dev
      - name: Lint (ruff)
        run: |
          uv run ruff format --check src/ tests/
          uv run ruff check src/ tests/
      - name: Tests
        run: |
          uv run pytest -q --cov=src --cov-report=xml
      - name: Build package
        run: |
          uv build
