name: Protect main branch

on:
  workflow_dispatch:

permissions:
  contents: read
  administration: write

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main with branch protection API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          # Configure classic branch protection for `main`.
          # Adjust status checks in the JSON if you add more CI jobs.
          cat >payload.json <<'JSON'
          {
            "required_status_checks": {
              "strict": true,
              "contexts": [
                "Generate Documentation / docs"
              ]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": null,
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "block_creations": true,
            "required_conversation_resolution": true
          }
          JSON

          curl -sS -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/branches/main/protection \
            --data @payload.json
